name: Trivy scan workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          version: latest

      #anything w high/crit will be prevented when running 
      - name: Security gate - Fail if HIGH or CRITICAL vulns in NGINX
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL nginx:1.21

      - name: Scan NGINX image (JSON)
        run: trivy image -f json -o nginx-report.json nginx:1.21

      - name: Scan NGINX image (HTML)
        run: trivy image -f template --template "@contrib/html.tpl" -o nginx-report.html nginx:1.21

      - name: Scan Alpine image (JSON)
        run: trivy image -f json -o alpine-report.json alpine:3.12

      - name: Scan Alpine image (HTML)
        run: trivy image -f template --template "@contrib/html.tpl" -o alpine-report.html alpine:3.12

      - name: Upload Trivy scan reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-reports
          path: |
            nginx-report.json
            nginx-report.html
            alpine-report.json
            alpine-report.html

