name: Trivy scan workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.1

      - name: Scan NGINX image
        run: trivy image --severity CRITICAL,HIGH nginx:latest

      - name: Scan Alpine image
        run: trivy image --severity CRITICAL,HIGH alpine:latest

      - name: Upload Trivy scan report
        if: always()
        run: |
          trivy image -f json -o trivy-report.json nginx:latest
          trivy image -f json -o trivy-report-alpine.json alpine:latest
        continue-on-error: true

      - name: Save scan results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: |
            trivy-report.json
            trivy-report-alpine.json

